codestates-seb/seb45_main_026

Server/.gitignore
Server/build.gradle
Server/settings.gradle
Server/src/main/java/com/server/module/s3/config/S3Config.java
Server/src/main/java/com/server/module/s3/service/S3Service.java
Server/src/main/java/com/server/module/s3/service/S3ServiceImpl.java
Server/src/main/resources/application.yml

:sparkle: feat : s3 의존성 추가, interface 작성

---

Server/src/main/java/com/server/auth/SecurityConfig.java
Server/src/main/java/com/server/auth/controller/AuthController.java
Server/src/main/java/com/server/auth/controller/dto/AuthApiRequest.java
Server/src/main/java/com/server/auth/service/AuthService.java
Server/src/main/java/com/server/domain/member/entity/Authority.java
Server/src/main/java/com/server/domain/member/entity/Member.java
Server/src/main/java/com/server/domain/member/repository/MemberRepository.java
Server/src/main/java/com/server/domain/member/service/MemberService.java
Server/src/main/java/com/server/domain/member/service/dto/MemberServiceRequest.java
Server/src/main/java/com/server/global/exception/businessexception/mailexception/MailCertificationException.java
Server/src/main/java/com/server/global/exception/businessexception/mailexception/MailException.java
Server/src/main/java/com/server/global/exception/businessexception/mailexception/MailSendException.java
Server/src/main/java/com/server/module/email/config/MailConfig.java
Server/src/main/java/com/server/module/email/service/MailService.java
Server/src/main/java/com/server/module/redis/service/RedisService.java
Server/src/main/resources/application.yml
Server/src/test/java/com/server/auth/AuthControllerTest.java

:sparkles: feat: 회원가입 기능 추가

---

Server/src/main/java/com/server/auth/SecurityConfig.java
Server/src/main/java/com/server/auth/controller/AuthController.java
Server/src/main/java/com/server/auth/controller/dto/AuthApiRequest.java
Server/src/main/java/com/server/auth/jwt/filter/JwtAuthenticationFilter.java
Server/src/main/java/com/server/auth/jwt/service/CustomUserDetails.java
Server/src/main/java/com/server/auth/jwt/service/JpaUserDetailsService.java
Server/src/main/java/com/server/auth/jwt/service/JwtProvider.java
Server/src/main/java/com/server/auth/service/AuthService.java
Server/src/main/java/com/server/auth/service/dto/AuthServiceRequest.java
Server/src/main/java/com/server/global/annotation/AnnotationConfig.java
Server/src/main/java/com/server/global/annotation/LoginId.java
Server/src/main/java/com/server/global/annotation/LoginIdConfigure.java

@LoginID 어노테이션 추가 완료
리프래쉬 토큰 미구현(예정)

:sparkles: feat: JWT 로컬 로그인 기능 추가 #7

---

Server/src/main/java/com/server/auth/SecurityConfig.java

https://www.itprometheus.net 추가

:sparkle: feat : cors 정책 변경 #17

---

Server/src/main/java/com/server/auth/SecurityConfig.java
Server/src/main/java/com/server/auth/controller/AuthController.java
Server/src/main/java/com/server/auth/controller/dto/AuthApiRequest.java
Server/src/main/java/com/server/auth/jwt/filter/JwtAuthenticationFilter.java
Server/src/main/java/com/server/auth/jwt/filter/JwtRefreshFilter.java
Server/src/main/java/com/server/auth/jwt/filter/JwtVerificationFilter.java
Server/src/main/java/com/server/auth/jwt/handler/MemberAuthenticationFailureHandler.java
Server/src/main/java/com/server/auth/jwt/handler/MemberAuthenticationSuccessHandler.java
Server/src/main/java/com/server/auth/jwt/service/CustomUserDetails.java
Server/src/main/java/com/server/auth/jwt/service/JpaUserDetailsService.java
Server/src/main/java/com/server/auth/jwt/service/JwtProvider.java
Server/src/main/java/com/server/auth/service/AuthService.java
Server/src/main/java/com/server/auth/util/AuthConstant.java
Server/src/main/java/com/server/global/exception/businessexception/authexception/AuthException.java
Server/src/main/java/com/server/global/exception/businessexception/authexception/JwtExpiredException.java
Server/src/main/java/com/server/global/exception/businessexception/authexception/JwtNotFoundException.java
Server/src/main/java/com/server/global/exception/businessexception/authexception/JwtNotValidException.java
Server/src/main/java/com/server/global/exception/businessexception/mailexception/MailCertificationException.java
Server/src/main/java/com/server/global/exception/businessexception/mailexception/MailSendException.java
Server/src/main/java/com/server/global/exception/businessexception/requestexception/RequestException.java
Server/src/main/java/com/server/global/exception/businessexception/requestexception/RequestNotPostException.java

1. 리프래시 토큰 기능 추가
2. 관련 예외 클래스 추가 및 수정
3. 시큐리티 전체 코드 리팩토링

:sparkles: feat: 리프래시 토큰 추가 및 로그인 리팩토링 #21

---

Server/src/main/java/com/server/domain/order/controller/OrderController.java
Server/src/main/java/com/server/domain/order/controller/dto/request/OrderCreateApiRequest.java
Server/src/main/java/com/server/domain/order/controller/dto/response/PaymentApiResponse.java
Server/src/main/java/com/server/domain/order/entity/Order.java
Server/src/main/java/com/server/domain/order/entity/OrderStatus.java
Server/src/main/java/com/server/domain/order/entity/OrderVideo.java
Server/src/main/java/com/server/domain/order/repository/OrderRepository.java
Server/src/main/java/com/server/domain/order/service/OrderService.java
Server/src/main/java/com/server/domain/order/service/dto/request/OrderCreateServiceRequest.java
Server/src/main/java/com/server/domain/order/service/dto/response/OrderResponse.java
Server/src/main/java/com/server/domain/order/service/dto/response/OrderVideoResponse.java
Server/src/main/java/com/server/domain/order/service/dto/response/PaymentServiceResponse.java
Server/src/main/java/com/server/domain/video/entity/Video.java
Server/src/main/java/com/server/domain/video/repository/VideoRepository.java
Server/src/main/java/com/server/global/exception/businessexception/orderexception/OrderException.java
Server/src/main/java/com/server/global/exception/businessexception/orderexception/RewardNotEnoughException.java
Server/src/test/java/com/server/domain/order/entity/OrderTest.java
Server/src/test/java/com/server/domain/order/service/OrderServiceTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java
Server/src/test/java/com/server/global/testhelper/RepositoryTest.java

orderService 추가 -> 주문 삭제, 추가, 결제 / 주문 목록 조회, 주문 여부 조회 로직 (미구현)
orderController 구현 중

:sparkle: feat : order 주문 및 결제 로직 추가 #22

---

Server/src/main/java/com/server/auth/jwt/filter/JwtAuthenticationFilter.java

:bug: fix: JWT BEARER 공백 추가 #21

---

Server/src/main/java/com/server/domain/video/aop/VideoStubAop.java
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/main/java/com/server/domain/video/controller/dto/request/VideoCreateApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/VideoCreateUrlApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/VideoUpdateApiRequest.java
Server/src/main/java/com/server/domain/video/entity/Video.java
Server/src/main/java/com/server/domain/video/service/VideoService.java
Server/src/main/java/com/server/domain/video/service/dto/request/VideoCreateServiceRequest.java
Server/src/main/java/com/server/domain/video/service/dto/request/VideoCreateUrlServiceRequest.java
Server/src/main/java/com/server/domain/video/service/dto/request/VideoUpdateServiceRequest.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoCategoryResponse.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoChannelResponse.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoCreateUrlResponse.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoDetailResponse.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoPageResponse.java
Server/src/main/java/com/server/global/exception/businessexception/s3exception/S3FileNotVaildException.java
Server/src/main/java/com/server/global/exception/businessexception/s3exception/S3KeyException.java
Server/src/main/java/com/server/module/s3/service/AwsService.java
Server/src/main/java/com/server/module/s3/service/AwsServiceImpl.java

- video controller 작성
- video controller stub 데이터 작성 완료

:sparkles: feat : videoController stub 데이터 작성 #42

---

client/src/index.js
client/src/redux/Store.js
client/src/redux/createSlice/LoginInfoSlice.js

구현한 기능이 무엇인가요?
- Redux-toolkit 초기 설정
해당 기능의 세부사항에는 무엇이 있나요?

[FE] Redux-toolkit 초기 설정

---

client/.storybook/preview.js
client/src/atoms/Buttons.stories.js
client/src/atoms/IconButtons.js
client/src/atoms/Inputs.js
client/src/atoms/Inputs.stories.js
client/src/atoms/PageContainer.js

- icon button, input 구현
- IconButtons.js 작성
- Inputs.js 작성

✨ [FE] feat : 아토믹 디자인 - icon button, input 구현

---

Server/src/main/java/com/server/domain/member/controller/MemberController.java
Server/src/main/java/com/server/domain/member/service/MemberService.java
Server/src/main/java/com/server/global/annotation/LoginIdConfigure.java
Server/src/test/java/com/server/domain/member/controller/MemberControllerTest.java
Server/src/test/java/com/server/global/testhelper/ControllerTest.java

@LoginId 어노테이션도 컨텍스트에서 어센티케이션 가져올 때 널포인터 뜨길래 조건 추가해놨어요!

[BE] :memo: docs: 컨트롤러 공통화 테스트 클래스 추가 및 간단한 테스트 코드 작성 #58

---

Server/Dockerfile

:recycle: refactor: dockerFile 수정 #17

---

Server/src/main/java/com/server/module/s3/service/AwsServiceImpl.java

구현한 기능
- image 용 s3 버킷 위치 지정
- cloudfront https 통신으로 변경
해당 기능 세부사항
- image, thumbnail 은 공개된 리소스이므로 public s3 버킷으로 변경
- 해당 리소스들은 서버에서 s3 로 presignedurl 을 요청하지 않기 때문에 get 요청 시 부하 감소

[BE] image, video 버킷 위치 나누기

---

Server/src/test/java/com/server/module/s3/service/AwsServiceTest.java

구현한 기능이 무엇인가요?
- awsServiceTest 확인, 주석해제
해당 기능의 세부사항에는 무엇이 있나요?

[BE] awsServiceTest 확인, 주석해제 #17

---

Server/src/main/java/com/server/domain/announcement/aop/AnnouncementStubAop.java
Server/src/main/java/com/server/domain/announcement/controller/AnnouncementController.java
Server/src/main/java/com/server/domain/announcement/controller/dto/request/AnnouncementUpdateApiRequest.java
Server/src/main/java/com/server/domain/announcement/entity/Announcement.java
Server/src/main/java/com/server/domain/announcement/service/AnnouncementService.java
Server/src/main/java/com/server/domain/announcement/service/dto/request/AnnouncementCreateServiceRequest.java
Server/src/main/java/com/server/domain/announcement/service/dto/request/AnnouncementUpdateServiceRequest.java
Server/src/main/java/com/server/domain/announcement/service/dto/response/AnnouncementResponse.java
Server/src/main/java/com/server/domain/channel/aop/ChannelStubAop.java
Server/src/main/java/com/server/domain/channel/controller/ChannelController.java
Server/src/main/java/com/server/domain/channel/entity/Channel.java
Server/src/main/resources/application.yml
Server/src/test/java/com/server/global/testhelper/ControllerTest.java

구현한 기능이 무엇인가요?
- ex) announcement controller 생성
해당 기능의 세부사항에는 무엇이 있나요?

[BE ] announcement controller 생성 및 stub 데이터 추가

---

Server/src/main/resources/application.yml

구현한 기능이 무엇인가요?
- yml 파일에 mysql ddlauto : create drop 으로 변경

[BE] yml 파일에 mysql ddlauto : create drop 으로 변경

---

client/src/App.js
client/src/pages/auth/LoginPage.js
client/src/pages/contents/MainPage.js
client/src/pages/userInfo/MyProfilePage.js
client/src/redux/createSlice/UISettingSlice.js

- location state 삭제
- 굳이 redux 쓰지 않아도 url.pathname으로 조건부 랜더링 할 수 있음

[FE] location state 삭제

---

client/src/App.js
client/src/components/contentListItem/HorizonItem.js
client/src/components/contentListItem/VerticalItem.js
client/src/pages/contents/ChannelPage.js
client/src/styles/tokens.json

구현한 기능이 무엇인가요?
가로 형태 컴포넌트 목업
해당 기능의 세부사항에는 무엇이 있나요?
CSS 설정

[FE] 가로 형태 컴포넌트 목업

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/atoms/buttons/Buttons.js
client/src/atoms/inputs/Inputs.js
client/src/atoms/layouts/PageContainer.js
client/src/components/footers/Footer.js
client/src/components/headers/Header.js
client/src/components/headers/Header.style.js
client/src/components/loginPageItems/ExtraButton.js
client/src/components/loginPageItems/Login.js
client/src/components/loginPageItems/LoginForm.js
client/src/components/loginPageItems/LoginForm.style.js
client/src/components/loginPageItems/LoginLogo.js
client/src/components/loginPageItems/SNSLogin.js
client/src/components/loginPageItems/SNSLogin.style.js
client/src/components/mainPageItems/MainPageItems.js
client/src/components/mainPageItems/MainPageItems.style.js
client/src/pages/auth/LoginPage.js
client/src/pages/contents/MainPage.style.js
client/src/redux/createSlice/UISettingSlice.js
client/src/services/authServices.js
client/src/styles/tokens.json

- 로그인 페이지 디자인 / 기능 구현
- 로그인 페이지 컴포넌트 짜기
- react hook form 적용
- Google OAuth

[FE] 로그인 페이지 디자인 / 기능 구현

---

Server/src/docs/asciidoc/index.adoc
Server/src/docs/asciidoc/snippets/announcement/docinfo.html
Server/src/docs/asciidoc/snippets/common/answerstatus.adoc
Server/src/docs/asciidoc/snippets/common/imagetype.adoc
Server/src/docs/asciidoc/snippets/common/orderstatus.adoc
Server/src/docs/asciidoc/snippets/common/videosort.adoc
Server/src/docs/asciidoc/snippets/question/cudquestion.adoc
Server/src/docs/asciidoc/snippets/question/docinfo.html
Server/src/docs/asciidoc/snippets/question/getquestion.adoc
Server/src/docs/asciidoc/snippets/question/solvequestion.adoc
Server/src/docs/asciidoc/snippets/video/cartvideo.adoc
Server/src/docs/asciidoc/snippets/video/createvideo.adoc
Server/src/docs/asciidoc/snippets/video/docinfo.html
Server/src/docs/asciidoc/snippets/video/getvideo.adoc
Server/src/docs/asciidoc/snippets/video/updatedeletevideo.adoc
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java
Server/src/test/java/com/server/global/restdocs/CommonControllerTest.java

[BE] 📝 video restdocs 문서화 완료 #42

---

client/.storybook/preview.js
client/src/atoms/buttons/Buttons.js
client/src/atoms/buttons/Buttons.stories.js
client/src/atoms/buttons/Checkbox.js
client/src/atoms/buttons/Checkbox.stories.js
client/src/atoms/inputs/Inputs.js
client/src/atoms/inputs/TextAreas.js
client/src/components/headers/Header.style.js
client/src/components/loginPageItems/LoginForm.js
client/src/components/loginPageItems/LoginForm.style.js
client/src/pages/contents/MainPage.style.js
client/src/styles/tokens.json

- textarea 아토믹 디자인 추가
- tokens.json 색상 변경 ( 배경색 오렌지 -> 붉은색으로 변경,,, )
- checkbox 아토믹 디자인 추가
- button 아토믹 디자인 추가

[FE] 아토믹 디자인 수정 & 추가

---

Server/src/docs/asciidoc/snippets/question/cudquestion.adoc
Server/src/docs/asciidoc/snippets/question/getquestion.adoc
Server/src/docs/asciidoc/snippets/question/solvequestion.adoc
Server/src/main/java/com/server/domain/question/controller/QuestionController.java
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/test/java/com/server/domain/question/controller/QuestionControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java

[BE] :memo: question asciidocs 문서 생성 #12

---

client/src/App.js
client/src/components/SignupPageItems/SignupForm.js
client/src/components/SignupPageItems/SignupForm.style.js
client/src/components/SignupPageItems/SignupInput.js
client/src/components/loginPageItems/ExtraButton.js
client/src/components/loginPageItems/LoginForm.js
client/src/pages/auth/SignupPage.js
client/src/redux/createSlice/LoginInfoSlice.js
client/src/services/authServices.js

- 회원가입 기능 구현
- 로그인 기능 구현
- 로그인 service return 값

[FE] 로그인, 회원가입 기능 구현

---

Server/src/docs/asciidoc/index.adoc
Server/src/docs/asciidoc/snippets/announcement/getannouncement.adoc
Server/src/docs/asciidoc/snippets/channel/docinfo.html
Server/src/docs/asciidoc/snippets/channel/getchannel.adoc
Server/src/docs/asciidoc/snippets/question/cudquestion.adoc
Server/src/docs/asciidoc/snippets/question/getquestion.adoc
Server/src/docs/asciidoc/snippets/question/solvequestion.adoc
Server/src/docs/asciidoc/snippets/video/cartvideo.adoc
Server/src/docs/asciidoc/snippets/video/createvideo.adoc
Server/src/docs/asciidoc/snippets/video/getvideo.adoc
Server/src/main/java/com/server/domain/channel/aop/ChannelStubAop.java
Server/src/main/java/com/server/domain/channel/controller/ChannelController.java
Server/src/main/java/com/server/domain/channel/controller/dto/request/CreateAnnouncementApiRequest.java
Server/src/main/java/com/server/domain/channel/service/ChannelService.java
Server/src/main/java/com/server/domain/channel/service/dto/ChannelDto.java
Server/src/main/java/com/server/domain/channel/service/dto/request/ChannelVideoGetServiceRequest.java
Server/src/main/java/com/server/domain/channel/service/dto/response/ChannelVideoResponse.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryCustom.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryImpl.java
Server/src/test/java/com/server/domain/channel/controller/ChannelControllerTest.java
Server/src/test/java/com/server/domain/channel/service/ChannelServiceTest.java
Server/src/test/java/com/server/domain/question/service/QuestionServiceTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java
Server/src/test/java/com/server/domain/video/service/VideoServiceTest.java
Server/src/test/java/com/server/global/testhelper/RepositoryTest.java
Server/src/test/java/com/server/global/testhelper/ServiceTest.java

[BE] :sparkles: feat: channel 의 video 조회 기능 개발 및 테스트 완료 #42

---

client/src/components/filters/FilterDropdown.js
client/src/pages/contents/ChannelPage.js

[FE]디자인 일부 수정

---

client/src/App.js
client/src/components/SignupPageItems/SignupForm.js
client/src/components/SignupPageItems/SignupInput.js
client/src/components/headers/Header.js
client/src/components/loginPageItems/LoginForm.js
client/src/pages/contents/LectureListPage.js
client/src/redux/createSlice/LoginInfoSlice.js
client/src/services/authServices.js

- LectureListPage 생성, Route 설정 추가

[FE] 강의 목록 페이지 생성

---

client/src/atoms/layouts/PageContainer.js
client/src/components/contentListItems/ChannelHome.js
client/src/components/contentListItems/ChannelList.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/ListToggle.js
client/src/pages/contents/ChannelPage.js
client/src/pages/contents/LectureListPage.js
client/src/pages/contents/PurchasedListPage.js

[FE]강의목록 리스트 목업

---

client/src/App.js
client/src/atoms/buttons/Buttons.stories.js
client/src/atoms/buttons/Checkbox.js
client/src/atoms/buttons/Checkbox.stories.js
client/src/atoms/inputs/TextAreas.js
client/src/components/SignupPageItems/SignupForm.js
client/src/components/SignupPageItems/SignupInput.js
client/src/components/loginPageItems/ExtraButton.js
client/src/components/loginPageItems/LoginForm.js
client/src/components/loginPageItems/LoginForm.style.js
client/src/components/loginPageItems/LoginInputs.js
client/src/hooks/useConfirm.js
client/src/pages/auth/FindPasswordPage.js
client/src/services/userInfoService.js

- checkbox 아토믹 디자인에 isChecked, isDark Props 추가
- 비밀번호 찾기 페이지 생성

[FE] 로그인/회원가입/비밀번호찾기/사용자인증

---

client/src/App.js
client/src/pages/contents/DetailPage/DetailPage.js
client/src/pages/contents/ProblemPage.js
client/src/redux/Store.js
client/src/redux/createSlice/VideoInfoSlice.js

- "강의 상세 페이지 서버 데이터 불러오기" 하나 잠깐 구현한 상태 입니다.

[Fe] 강의 상세 페이지 서버 데이터 불러오기

---

client/src/App.js
client/src/components/headers/Header.js
client/src/pages/contents/MainPage.js

[FE] 프로필 조회 실패 시 팝업 뜨는 기능 추가

---

client/src/pages/contents/MainPage.js

[FE] 로그인여부 판단하는 코드 수정

---

Server/src/main/java/com/server/domain/reward/entity/Reward.java
Server/src/main/java/com/server/domain/reward/service/RewardService.java
Server/src/main/java/com/server/domain/video/controller/dto/request/VideoUpdateApiRequest.java
Server/src/main/java/com/server/domain/video/entity/Video.java
Server/src/main/java/com/server/domain/video/entity/VideoStatus.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryCustom.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryImpl.java
Server/src/main/java/com/server/domain/video/service/VideoService.java
Server/src/main/java/com/server/domain/video/service/dto/request/VideoUpdateServiceRequest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java
Server/src/test/java/com/server/domain/video/entity/VideoTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java
Server/src/test/java/com/server/domain/video/service/VideoServiceTest.java
Server/src/test/java/com/server/global/testhelper/RepositoryTest.java
Server/src/test/java/com/server/global/testhelper/ServiceTest.java

- videoStatus 필드 추가
- video 수정 시 description 만 받도록 변경

[BE] videoStatus 구현, video 수정 API 변경 #42

---

Server/src/main/java/com/server/domain/order/entity/Order.java
Server/src/main/java/com/server/domain/order/service/OrderService.java
Server/src/main/java/com/server/domain/reward/entity/Reward.java
Server/src/main/java/com/server/domain/reward/service/RewardService.java
Server/src/test/java/com/server/domain/order/entity/OrderTest.java
Server/src/test/java/com/server/domain/order/service/OrderServiceTest.java
Server/src/test/java/com/server/domain/reward/service/RewardServiceTest.java
Server/src/test/java/com/server/global/testhelper/ServiceTest.java

-  video 결제 시 reward 적립 및 취소 관련 테스트 케이스 완료

[BE] :sparkles: feat: video 결제 시 reward 적립 및 취소 관련 테스트 케이스 작성 완료 #22

---

Server/src/main/java/com/server/domain/answer/entity/Answer.java
Server/src/main/java/com/server/domain/answer/repository/AnswerRepository.java
Server/src/main/java/com/server/domain/question/repository/QuestionRepository.java
Server/src/main/java/com/server/domain/question/service/QuestionService.java
Server/src/main/java/com/server/domain/reward/entity/Reward.java
Server/src/main/java/com/server/domain/reward/repository/RewardRepository.java
Server/src/main/java/com/server/domain/reward/service/RewardService.java
Server/src/main/java/com/server/domain/video/repository/VideoRepository.java
Server/src/main/java/com/server/global/exception/businessexception/answerexception/AnswerCountException.java
Server/src/main/java/com/server/global/exception/businessexception/answerexception/AnswerNotFoundException.java
Server/src/test/java/com/server/domain/answer/entity/AnswerTest.java
Server/src/test/java/com/server/domain/answer/repository/AnswerRepositoryTest.java
Server/src/test/java/com/server/domain/order/repository/OrderRepositoryTest.java
Server/src/test/java/com/server/domain/question/repository/QuestionRepositoryTest.java
Server/src/test/java/com/server/domain/question/service/QuestionServiceTest.java
Server/src/test/java/com/server/domain/reward/repository/RewardRepositoryTest.java
Server/src/test/java/com/server/domain/reward/service/RewardServiceTest.java
Server/src/test/java/com/server/global/testhelper/RepositoryTest.java

- questionService 에 solveQuestion, solveQuestions 구현
- rewardService 에 Question 관련 로직 구현
- 테스트 코드 작성 완료

[BE] :sparkles: feat : question 을 풀 때 reward 적립 기능 구현 #12

---

Server/src/main/java/com/server/domain/channel/controller/ChannelController.java
Server/src/main/java/com/server/domain/channel/service/ChannelService.java
Server/src/main/java/com/server/domain/channel/service/dto/request/ChannelVideoGetServiceRequest.java
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryCustom.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryImpl.java
Server/src/main/java/com/server/domain/video/repository/dto/VideoGetDataRequest.java
Server/src/main/java/com/server/domain/video/service/VideoService.java
Server/src/main/java/com/server/domain/video/service/dto/request/VideoGetServiceRequest.java
Server/src/test/java/com/server/domain/channel/controller/ChannelControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java
Server/src/test/java/com/server/domain/video/service/VideoServiceTest.java
Server/src/test/java/com/server/global/testhelper/RepositoryTest.java

- videoController  에서 video 검색 조건으로 free 추가
- channelController 에서 channel 내 검색 조건으로 Free 추가

[BE]✨ video 전체 조회 시 유/무류 강의 구분 free 값 추가 #42

---

Server/src/docs/asciidoc/index.adoc
Server/src/docs/asciidoc/snippets/channel/getchannel.adoc
Server/src/docs/asciidoc/snippets/channel/subscribechannel.adoc
Server/src/docs/asciidoc/snippets/channel/updatechannel.adoc
Server/src/main/java/com/server/domain/channel/aop/ChannelStubAop.java
Server/src/main/java/com/server/domain/channel/controller/ChannelController.java
Server/src/main/java/com/server/domain/channel/controller/dto/request/CreateAnnouncementApiRequest.java
Server/src/main/java/com/server/domain/channel/service/dto/ChannelInfo.java
Server/src/main/java/com/server/domain/channel/service/dto/ChannelUpdate.java
Server/src/main/resources/messages.properties
Server/src/test/java/com/server/domain/channel/controller/ChannelControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java

- channel controller 테스트 작성
- channel controller API 문서화
- - channel controller validation 추가
- channel controller Validation 테스트 작성

[BE] :memo: docs : channel controller API 문서화 #152

---

Server/src/main/java/com/server/auth/aop/AuthInitializer.java
Server/src/main/java/com/server/domain/announcement/controller/AnnouncementController.java
Server/src/main/java/com/server/domain/announcement/controller/dto/request/AnnouncementUpdateApiRequest.java
Server/src/main/resources/application.yml
Server/src/test/java/com/server/domain/announcement/controller/AnnouncementControllerTest.java

- AnnouncementController 에 validation 추가
- AnnouncementControllerTest 에 validation 테스트 추가

[BE]✅ test : announcement validation 추가 #71

---

Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/main/java/com/server/domain/video/controller/dto/request/AnswersCreateApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/QuestionCreateApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/VideoCreateApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/VideoCreateUrlApiRequest.java
Server/src/main/resources/messages.properties
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java

- videoController validation 어노테이션 추가
- videoControllerTest 검증 테스트 추가

[BE]✅ : test video validation test 추가 #42

---

Server/src/main/java/com/server/domain/question/controller/QuestionController.java
Server/src/main/java/com/server/domain/question/controller/dto/request/AnswerCreateApiRequest.java
Server/src/main/java/com/server/domain/question/controller/dto/request/QuestionUpdateApiRequest.java
Server/src/main/java/com/server/global/validation/EachNotBlank.java
Server/src/main/java/com/server/global/validation/EachNotBlankValidator.java
Server/src/main/java/com/server/global/validation/OnlyNotBlank.java
Server/src/main/java/com/server/global/validation/OnlyNotBlankValidator.java
Server/src/main/resources/messages.properties
Server/src/test/java/com/server/domain/question/controller/QuestionControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java

- questionController validation 추가
- validation test 작성

[BE]✅ : test question validation test 추가 #12

---

Server/src/main/java/com/server/domain/question/controller/dto/request/AnswerCreateApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/AnswersCreateApiRequest.java
Server/src/main/java/com/server/domain/video/controller/dto/request/QuestionCreateApiRequest.java
Server/src/main/resources/messages.properties
Server/src/test/java/com/server/domain/question/controller/QuestionControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java

- question 생성 시 Selection 검증 추가
- question 풀기 시 selection 검증 추가

[BE] ✅ : test : video valiation 추가(question Selection) #42

---

Server/src/main/java/com/server/domain/announcement/aop/AnnouncementStubAop.java
Server/src/main/java/com/server/domain/channel/aop/ChannelStubAop.java
Server/src/main/java/com/server/domain/member/aop/MemberStubAop.java
Server/src/main/java/com/server/domain/order/aop/OrderStubAop.java
Server/src/main/java/com/server/domain/question/aop/QuestionStubAop.java
Server/src/main/java/com/server/domain/video/aop/VideoStubAop.java
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/main/resources/application.yml

- 각 컨트롤러에 Aop 해제
- 배포 환경 ddl-auto : none

[BE] :recycle: refactor 1차 개발자 테스트를 위한 배포(aop 해제) #17

---

client/src/App.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/VerticalItem.js
client/src/components/filters/CategoryFilter.js
client/src/components/filters/FilterDropdown.js
client/src/components/headers/Header.js
client/src/pages/contents/LectureListPage.js
client/src/pages/contents/PurchasedListPage.js

- purchasedpage 라우트 추가 및 일부 css수정 pr

[FE] purchasedpage라우트 추가 및 일부 css수정 pr

---

Server/src/docs/asciidoc/index.adoc
Server/src/docs/asciidoc/snippets/common/replysort.adoc
Server/src/docs/asciidoc/snippets/reply/docinfo.html
Server/src/docs/asciidoc/snippets/reply/getreply.adoc
Server/src/docs/asciidoc/snippets/reply/replycud.adoc
Server/src/main/java/com/server/domain/reply/controller/ReplyController.java
Server/src/main/java/com/server/domain/reply/controller/convert/ReplySort.java
Server/src/main/java/com/server/domain/reply/controller/convert/StringToReplySortConverter.java
Server/src/main/java/com/server/domain/reply/dto/ReplyCreateControllerApi.java
Server/src/main/java/com/server/domain/reply/dto/ReplyInfo.java
Server/src/main/java/com/server/domain/reply/dto/ReplyUpdateControllerApi.java
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryImpl.java
Server/src/test/java/com/server/domain/reply/controller/ReplyControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java
Server/src/test/java/com/server/global/restdocs/CommonControllerTest.java

- replycontrollerTest 추가
- reply API 문서화

[BE] :memo: docs : reply API 문서 추가 #152

---

Server/src/main/java/com/server/domain/question/entity/Question.java
Server/src/main/java/com/server/domain/reply/entity/Reply.java
Server/src/main/java/com/server/domain/reward/entity/NewReward.java
Server/src/main/java/com/server/domain/reward/entity/QuestionReward.java
Server/src/main/java/com/server/domain/reward/entity/ReplyReward.java
Server/src/main/java/com/server/domain/reward/entity/RewardType.java
Server/src/main/java/com/server/domain/reward/entity/Rewardable.java
Server/src/main/java/com/server/domain/reward/entity/VideoReward.java
Server/src/main/java/com/server/domain/reward/repository/NewRewardRepository.java
Server/src/main/java/com/server/domain/reward/repository/NewRewardRepositoryCustom.java
Server/src/main/java/com/server/domain/reward/repository/NewRewardRepositoryImpl.java
Server/src/main/java/com/server/domain/reward/service/RewardService.java
Server/src/main/java/com/server/domain/video/entity/Video.java
Server/src/test/java/com/server/domain/reward/repository/NewRewardRepositoryTest.java

newReward -> 각각 QuestionReward, ReplyReward, VideoReward 를 가짐
newRewardRepository 생성

[BE] :recycle: refactor : newReward 엔티티 개발 #170

---

client/src/App.js
client/src/atoms/buttons/Checkbox.js
client/src/atoms/buttons/Checkbox.stories.js
client/src/components/SignupPageItems/SignupForm.js
client/src/components/SignupPageItems/SignupForm.style.js
client/src/components/SignupPageItems/SignupInput.js
client/src/components/findPasswordPageItems/FindPasswordPageForm.js
client/src/components/findPasswordPageItems/FindPasswordPageInput.js
client/src/components/footers/Footer.js
client/src/components/headers/Header.js
client/src/components/sideBar/SideBar.js
client/src/pages/auth/FindPasswordPage.js
client/src/pages/auth/SignupPage.js
client/src/services/authServices.js

- useMatch를 이용하여 Main Page 헤더 변경되도록 기능 추가 
- logout 기능 구현, 사이드바 navigate 일부 구현
- 문의하기 누르면 메일 앱 실행되도록 기능 추가
- 회원가입 할 때 이메일 인증 누르면 이메일만 유효성검사 되도록 기능 보강
- 비밀번호 찾기 목업 작성, 비밀번호 찾기 이메일 유효성 검사 기능 구현

[FE] 사용자 인증 목업 & 기능 구현

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/CartPage/CartItem.js
client/src/components/CartPage/CartPayInfo.js
client/src/components/headers/Header.js
client/src/pages/auth/LoginPage.js
client/src/pages/contents/CartPage/CartLeft.js
client/src/pages/contents/CartPage/CartPage.js
client/src/pages/contents/DetailPage/DetailContent.js
client/src/pages/contents/DetailPage/DetailPage.js
client/src/pages/contents/DetailPage/DetailVideo.js
client/src/pages/contents/LectureListPage.js
client/src/pages/contents/MainPage.js
client/src/pages/contents/ProblemPage.js
client/src/redux/Store.js
client/src/redux/createSlice/CartsSlice.js
client/src/redux/createSlice/UISettingSlice.js
client/src/redux/createSlice/VideoInfoSlice.js

[FE] 비디오 출력

---

Server/src/main/java/com/server/domain/reply/controller/ReplyController.java
Server/src/main/java/com/server/domain/reply/dto/ReplyCreateControllerApi.java
Server/src/main/java/com/server/domain/reply/dto/ReplyUpdateControllerApi.java
Server/src/main/java/com/server/domain/video/controller/VideoController.java
Server/src/main/resources/messages.properties
Server/src/test/java/com/server/domain/reply/controller/ReplyControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java

- replyController -> getreply, updatereply, deletereply validation 테스트 작성
- videoController -> getreplies, createreply validation 테스트 작성

[BE] :memo: docs: reply 기능 validation 테스트 완료 #152

---

client/src/components/contentListItems/PurchasedItem.js
client/src/pages/contents/LectureListPage.js
client/src/pages/contents/PurchasedListPage.js

[FE]채널별 목업 1차

---

Server/src/main/java/com/server/domain/channel/service/dto/response/ChannelVideoResponse.java
Server/src/main/java/com/server/domain/order/service/OrderService.java
Server/src/main/java/com/server/domain/video/entity/Video.java
Server/src/main/java/com/server/domain/video/entity/VideoStatus.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryImpl.java
Server/src/main/java/com/server/domain/video/service/VideoService.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoPageResponse.java
Server/src/main/java/com/server/global/exception/businessexception/orderexception/VideoAlreadyWatchedException.java
Server/src/main/java/com/server/global/exception/businessexception/videoexception/VideoClosedException.java
Server/src/test/java/com/server/domain/channel/controller/ChannelControllerTest.java
Server/src/test/java/com/server/domain/channel/service/ChannelServiceTest.java
Server/src/test/java/com/server/domain/order/service/OrderServiceTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java
Server/src/test/java/com/server/domain/video/service/VideoServiceTest.java

- video closed 상태 구현 : video 조회 시, 구매요청시, 장바구니 추가시 closed 면 요청 불가 처리
video 목록 반환 시 video description 함께 반환

♻️ refactor : video closed 상태 구현, video 목록 반환 시 video description 함께 반환 #42

---

Server/src/docs/asciidoc/index.adoc
Server/src/docs/asciidoc/snippets/order/cancelorder.adoc
Server/src/main/java/com/server/domain/order/controller/OrderController.java
Server/src/main/java/com/server/domain/order/controller/dto/response/VideoCancelApiResponse.java
Server/src/main/java/com/server/domain/order/entity/OrderVideo.java
Server/src/main/java/com/server/domain/order/service/OrderService.java
Server/src/main/java/com/server/domain/order/service/dto/response/VideoCancelServiceResponse.java
Server/src/test/java/com/server/domain/order/controller/OrderControllerTest.java
Server/src/test/java/com/server/domain/order/service/OrderServiceTest.java

- orderController 에 cancelVideo 생성
- Test 작성 완료(API 문서화)
- 기능 미구현

[BE] ✨ feat : 개별 비디오 취소 기능 controller 생성 및 문서화

---

client/src/App.js
client/src/atoms/buttons/Checkbox.js
client/src/atoms/inputs/Inputs.js
client/src/atoms/inputs/Inputs.stories.js
client/src/components/contentListItems/ChannelNav.js
client/src/components/contentListItems/Setting.js
client/src/components/contentListItems/Setting.style.js
client/src/components/loginPageItems/SNSLogin.js
client/src/components/sideBar/SideBar.js
client/src/pages/contents/ChannelPage.js
client/src/redux/createSlice/LoginInfoSlice.js
client/src/services/userInfoService.js

- 내 프로필로 이동하도록 구현
- 내프로필 목업 작성
- 프로필 조회 API, 프로필 변경 API, 비밀번호 변경 API 연결
- 회원 탈퇴 서비스만 작성해둠 (연결도 해야됨)

[FE] 내 프로필 기능 구현

---

client/src/App.js
client/src/components/channelListItems/ChannelListItem.js
client/src/components/contentListItems/ChannelHome.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/PurchasedItem.js
client/src/components/contentListItems/VerticalItem.js
client/src/components/filters/CategoryButton.js
client/src/components/filters/CategoryFilter.js
client/src/components/filters/FilterDropdown.js
client/src/pages/contents/ChannelListPage.js
client/src/pages/contents/ChannelPage.js
client/src/pages/contents/LectureListPage.js
client/src/redux/createSlice/FilterSlice.js

[FE] 강의목록api연결 및 필터 테스트

---

client/src/components/contentListItems/ChannelHome.js
client/src/components/contentListItems/ChannelList.js
client/src/components/contentListItems/PurchasedItem.js
client/src/pages/contents/LectureListPage.js

[FE]채널페이지 임시 연결

---

client/src/components/contentListItems/Setting.js
client/src/components/sideBar/SideBar.js

[FE] 사이드바에 구매한 강의 페이지 연결

---

client/src/components/contentListItems/ChannelNav.js
client/src/pages/contents/ChannelPage.js

[FE] merge 후 기능 확인

---

Server/src/main/java/com/server/domain/channel/service/ChannelService.java
Server/src/main/java/com/server/domain/channel/service/dto/response/ChannelVideoResponse.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryCustom.java
Server/src/main/java/com/server/domain/video/repository/VideoRepositoryImpl.java
Server/src/main/java/com/server/domain/video/service/VideoService.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoDetailResponse.java
Server/src/main/java/com/server/domain/video/service/dto/response/VideoPageResponse.java
Server/src/test/java/com/server/domain/channel/controller/ChannelControllerTest.java
Server/src/test/java/com/server/domain/video/controller/VideoControllerTest.java
Server/src/test/java/com/server/domain/video/repository/VideoRepositoryTest.java

- videoController 에서 video 목록 조회 시 isInCart 추가
- videoController VideoDetail 조회 시 isInCart 추가
- channelCOntroller 에서 video 목록 조회 시 isInCart 추가

[BE] ✨ feat : video 목록 및 상세 조회 시 isInCart 추가 #42

---

Server/src/main/java/com/server/domain/channel/service/ChannelService.java
Server/src/main/java/com/server/domain/video/service/VideoService.java

미인증 시 반드시 false 인 값(구독 여부, 구매 여부, isReply, isInCart) 는 DB 조회를 하지 않고 바로 False 반환

[BE] :recycle: refactor : 미인증 시 구독, 구매, 장바구니 여부는 db 미조회 #42

---

client/src/App.js
client/src/services/authServices.js
client/src/services/userInfoService.js

- authorization 토큰이 만료되면 refresh로 토큰 재발급받도록 기능 추가

[FE] authorization 토큰이 만료되면 refresh로 토큰 재발급받도록 기능 추가 #223

---

client/src/atoms/modal/Modal.js

[FE] 모달창 다크모드 적용되도록 수정#222

---

client/src/pages/auth/LoginPage.js

[FE] 로그인페이지 테스트 로딩 없앰

---

client/src/App.js
client/src/atoms/inputs/ImageInput.js
client/src/atoms/layouts/PageContainer.js
client/src/components/contentListItems/ChannelHome.js
client/src/components/contentListItems/ChannelNav.js
client/src/components/contentListItems/Setting.js
client/src/components/contentListItems/Setting.style.js
client/src/components/headers/HeaderProfile.js
client/src/components/headers/HeaderProfile.style.js
client/src/pages/auth/LoginPage.js
client/src/pages/contents/ChannelPage.js
client/src/services/userInfoService.js

- 프로필 이미지 CRUD
- 헤더 프로필이미지 조회 기능 추가
근데 프로필 이미지 설정한 상태에서 다른 사진으로 바꾸는게 안됨..

[FE] 프로필 이미지 CRUD

---

client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/PurchasedItem.js

[FE]가격 표기 오류 수정

---

client/src/components/contentListItems/ChannelList.js
client/src/components/contentListItems/ChannelNav.js
client/src/components/contentListItems/ChannelNotice.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/NoticeItem.js
client/src/components/contentListItems/VerticalItem.js
client/src/pages/contents/ChannelListPage.js
client/src/pages/contents/LectureListPage.js

[FE] 강의 목록, 채널 목록에 다크모드 적용

---

client/src/atoms/modal/Modal.js
client/src/pages/contents/LectureListPage.js

[FE] 토큰 만료되면 비디오 목록 조회 안되는 버그 수정

---

client/src/components/UploadPage/CourseUpload.js

[FE] 강의 업로드 로직 수정

---

client/src/App.js
client/src/components/contentListItems/Setting.js
client/src/components/sideBar/SideBar.js
client/src/hooks/useLogout.js
client/src/hooks/useToken.js

useLogout, useToken custom hook 작성 후 App.js의 유저 정보 조회 코드에 적용

[FE] useLogout, useToken custom hook 작성 후 App.js의 유저 정보 조회 코드에 적용 #298

---

client/package-lock.json
client/package.json
client/src/components/CartPage/CartItem.js
client/src/components/CartPage/CartMyInfo.js
client/src/components/CartPage/CartPayInfo.js
client/src/components/ProblemPage/ProblemBox.js
client/src/components/ProblemPage/SelectNum.js
client/src/components/UploadPage/CourseUpload.js
client/src/pages/contents/CartPage/CartLeft.js
client/src/pages/contents/CartPage/CartPage.js
client/src/pages/contents/CartPage/CartRight.js
client/src/pages/contents/CartPage/TossPayment.js
client/src/pages/contents/CourseUploadPage.js
client/src/pages/contents/DetailPage/DetailPage.js
client/src/pages/contents/DetailPage/DetailVideo.js
client/src/pages/contents/ProblemPage.js
client/src/pages/contents/PurchasedListPage.js
client/src/redux/createSlice/CartsSlice.js

[FE] 토스 페이먼츠 초기설정

---

client/src/atoms/modal/Modal.js
client/src/components/CartPage/CartItem.js
client/src/components/CartPage/CartPayInfo.js
client/src/components/DetailPage/SubscribeBtn.js
client/src/components/UploadPage/CourseUpload.js
client/src/hooks/useToken.js
client/src/pages/contents/CartPage/CartPage.js
client/src/pages/contents/CartPage/CartRight.js
client/src/pages/contents/CartPage/TossPayment.js
client/src/pages/contents/CourseUploadPage.js
client/src/pages/contents/DetailPage/DetailContent.js
client/src/pages/contents/DetailPage/DetailReview.js
client/src/redux/createSlice/CartsSlice.js

[FE] 리뷰 조회 요청 작업중

---

client/src/pages/contents/CartPage/TossPayment.js

[FE] 결제 링크 수정

---

client/package-lock.json
client/package.json
client/src/components/contentListItems/ChannelList.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/PurchasedItem.js
client/src/components/contentListItems/Stars.js
client/src/components/contentListItems/VerticalItem.js
client/src/pages/contents/LectureListPage.js
client/src/pages/contents/PurchasedListPage.js
client/src/redux/createSlice/FilterSlice.js

[FE]무한스크롤 구현

---

client/src/App.js
client/src/components/contentListItems/ChannelNav.js
client/src/components/headers/HeaderProfile.js
client/src/components/headers/HeaderProfile.style.js
client/src/components/loginPageItems/LoginForm.js
client/src/components/receiptPage/ReceiptDropdown.js
client/src/components/receiptPage/ReceiptItem.js
client/src/components/rewardPage/RewardCategory.js
client/src/components/rewardPage/RewardDropdown.style.js
client/src/index.js
client/src/pages/userInfo/ReceiptPage.js
client/src/pages/userInfo/RewardPage.js
client/src/services/receiptServices.js

[FE] 결제내역 페이지 기능 구현 중

---

client/src/components/receiptPage/ReceiptDropdown.js
client/src/components/receiptPage/ReceiptDropdown.style.js
client/src/components/receiptPage/ReceiptItem.js
client/src/pages/contents/LectureListPage.js
client/src/pages/userInfo/ReceiptPage.js
client/src/pages/userInfo/RewardPage.js

[FE] 결제내역 페이지 기능 구현 완료

---

client/src/components/contentListItems/ChannelNotice.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/NoticeItem.js
client/src/components/contentListItems/NoticeSubmit.js
client/src/components/contentListItems/PurchasedItem.js
client/src/components/contentListItems/VerticalItem.js
client/src/components/filters/CategoryFilter.js
client/src/pages/contents/ChannelPage.js

[FE]공지사항 삭제 기능 및 무한스크롤 구현

---

client/src/components/contentListItems/ChannelItem.js
client/src/components/sideBar/SideBar.js
client/src/pages/contents/ChannelListPage.js
client/src/pages/contents/ChannelPage.js
client/src/pages/contents/SubscribedListPage.js

[FE]구독한 채널 목록 추가

---

client/src/App.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/VerticalItem.js
client/src/components/filters/CategoryFilter.js
client/src/components/filters/FilterDropdown.js
client/src/pages/contents/ChannelListPage.js
client/src/pages/contents/ChannelPage.js
client/src/pages/contents/WatchedListPage.js
client/src/redux/createSlice/FilterSlice.js

[FE]시청한 강의 목록 구현

---

client/src/atoms/inputs/Inputs.js
client/src/components/UploadPage/Modal/UploadModal.js
client/src/components/loginPageItems/LoginForm.js

- react-hook-form input 태그 버그 수정, 문제 등록 팝업 다크모드 적용

[FE] react-hook-form input 태그 버그 수정, 문제 등록 팝업 다크모드 적용

---

client/src/atoms/buttons/Toggle.js
client/src/atoms/inputs/TextAreas.js
client/src/components/receiptPage/ReceiptArcodian.js
client/src/components/receiptPage/ReceiptArcodianItem.js
client/src/components/receiptPage/ReceiptArcodianItem.style.js
client/src/components/receiptPage/ReceiptItem.js
client/src/components/receiptPage/ReceiptItem.style.js
client/src/components/receiptPage/ReceiptListHeader.js
client/src/components/rewardPage/RewardItem.js
client/src/components/rewardPage/RewardListHeader.js
client/src/services/receiptServices.js

[FE] 결제내역 아코디언 기능 추가

---

client/src/atoms/buttons/ListToggle.js
client/src/components/UploadPage/Modal/SelectToggle.js
client/src/components/UploadPage/Modal/UploadModal.js
client/src/components/contentListItems/Searchsubmit.js
client/src/components/loginPageItems/LoginForm.js
client/src/redux/createSlice/CartsSlice.js

[FE] 다같이 머지 후 수정

---

client/src/atoms/buttons/ListToggle.js
client/src/atoms/inputs/TextAreas.js
client/src/components/DetailPage/ReviewList.js
client/src/components/UploadPage/CourseUpload.js
client/src/components/contentListItems/HorizonItem.js
client/src/components/contentListItems/PurchasedItem.js
client/src/components/contentListItems/Searchsubmit.js
client/src/pages/contents/DetailPage/DetailReview.js
client/src/pages/contents/LectureListPage.js

[FE] 머지 후 디자인 수정

---

client/src/components/contentListItems/ChannelNotice.js
client/src/components/contentListItems/NoticeItem.js
client/src/components/searchDropdown/SearchDropdown.js
client/src/pages/contents/WatchedListPage.js

[FE]공지사항 삭제 모달 연결

---

client/src/components/UploadPage/CourseUpload.js

[FE] 카테고리 선택 오류 수정

---

client/src/atoms/buttons/ListToggle.js
client/src/atoms/modal/Modal.js
client/src/components/CartPage/CartPayInfo.js
client/src/components/DetailPage/AddCart.js
client/src/components/DetailPage/ReviewList.js
client/src/components/DetailPage/VideoPlayer.js
client/src/components/UploadPage/CourseUpload.js
client/src/components/UploadPage/Modal/UploadModal.js
client/src/components/UploadPage/ProblemUpload.js
client/src/pages/contents/CartPage/CartPage.js
client/src/pages/contents/CartPage/TossPayment.js
client/src/pages/contents/DetailPage/DetailReview.js
client/src/pages/contents/DetailPage/DetailVideo.js

[FE] alert, confirm 커스텀 모달창 리팩토링

[FE] alert, confirm 커스텀 모달창 리팩토링

---

client/build-storybook.log
client/package-lock.json
client/package.json
client/src/App.js
client/src/components/incomePage/IncomeCategory.js
client/src/components/incomePage/IncomeHeader.js
client/src/components/incomePage/IncomeItem.js
client/src/components/mainPageItems/Carousel.js
client/src/components/mainPageItems/MainFourthPageItems.js
client/src/components/mainPageItems/MainSecondPageItems.js
client/src/components/receiptPage/ReceiptDropdown.js
client/src/components/receiptPage/ReceiptItem.js
client/src/components/receiptPage/ReceiptItem.style.js
client/src/components/rewardPage/RewardCategory.js
client/src/pages/contents/MainPage.js
client/src/pages/userInfo/IncomePage.js
client/src/pages/userInfo/ReceiptPage.js
client/src/services/incomeServices.js
client/src/services/receiptServices.js

[FE] storybook 배포, 정산 기능 추가

---

client/src/components/contentListItems/VerticalItem.js

[FE]verticalItem별 숫자 제거

---

client/src/components/CartPage/CartPayInfo.js
client/src/components/DetailPage/VideoPlayer.js

[FE] 포인트 사용 에러 수정

---

client/src/components/SignupPageItems/SignupForm.js

[FE] 회원가입 시 이메일 길이제한 20->30으로 수정함

---

client/src/components/DetailPage/SubscribeBtn.js
client/src/components/contentListItems/HorizonItem.js
client/src/pages/contents/DetailPage/DetailVideo.js

[FE] 로그인 안했을 시 접근 차단

---

client/package-lock.json
client/package.json
client/src/pages/contents/MainPage.js
client/src/pages/contents/MainPage.style.js

[FE] react pagination 슬라이더 적용

---

client/src/components/adminPageItems/ReportCategory.js
client/src/pages/admin/AdminDetail.js
client/src/pages/admin/AdminList.js
client/src/pages/contents/DetailPage/DetailVideo.js
client/src/services/adminService.js

- 신고 카테고리, 목록으로 가기 버튼 다크모드, 강의 비활성화 해제 기능 추가

[FE] 신고 카테고리, 목록으로 가기 버튼 다크모드, 강의 비활성화 해제 기능 추가

---

client/src/components/DetailPage/VideoPlayer.js
client/src/pages/contents/DetailPage/DetailVideo.js

[FE] 미리보기 영상 출력 오류 수정

---

admin/package-lock.json
admin/package.json
admin/src/index.tsx

- react query 설치 후 index.tsx 설정 추가

[FE] react query 설치 후 index.tsx 설정 추가

---

admin/src/atoms/layouts/PageContainer.tsx
admin/src/components/header/Header.style.tsx
admin/src/components/header/Header.tsx
admin/src/components/header/HeaderLogo.tsx
admin/src/components/header/HeaderNav.tsx
admin/src/components/header/HeaderProfile.tsx
admin/src/components/navBar/NavBar.tsx
admin/src/components/navBar/NavButton.tsx
admin/src/hooks/useLogout.ts
admin/src/pages/MemberPage.tsx
admin/src/pages/VideoPage.tsx
admin/src/redux/Store.ts
admin/src/redux/createSlice/loginInfoSlice.ts
admin/src/services/memberService.ts
admin/src/services/videoService.ts

- nav (헤더에 추가)
- nav component  (신고 화면에서 sub nav로 활용할 컴포넌트)
- video 목록 조회 (width react query)

[FE] nav, nav component , video 목록 조회 

---

client/src/App.js
client/src/atoms/inputs/Inputs.js
client/src/components/CartPage/CartMyInfo.js
client/src/components/CartPage/CartPayInfo.js
client/src/components/UploadPage/CourseUpload.js
client/src/components/contentListItems/Setting.js
client/src/components/headers/HeaderProfile.js
client/src/components/incomePage/AdjustmentItem.js
client/src/components/incomePage/IncomeItem.js
client/src/components/receiptPage/ReceiptArcodian.js
client/src/components/receiptPage/ReceiptArcodianItem.js
client/src/components/receiptPage/ReceiptArcodianItem.style.js
client/src/components/receiptPage/ReceiptDropdown.js
client/src/components/receiptPage/ReceiptItem.js
client/src/components/rewardPage/RewardCategory.js
client/src/pages/contents/CartPage/CartRight.js
client/src/pages/contents/ChannelListPage.js
client/src/pages/contents/ChannelPage.js
client/src/pages/contents/LectureListPage.js
client/src/pages/userInfo/AccountPage.js
client/src/pages/userInfo/IncomePage.js

[FE] 개인정보 조회/수정 기능

---

admin/src/atoms/layouts/PageContainer.tsx
admin/src/atoms/table/Tabel.tsx
admin/src/components/memberListPage/MemberListItem.tsx
admin/src/components/videoListPage/VideoListItem.tsx
admin/src/hooks/useToken.ts
admin/src/pages/MemberPage.tsx
admin/src/pages/VideoPage.tsx
admin/src/services/loginService.ts
admin/src/types/axiosErrorType.ts
client/src/components/contentListItems/Setting.js
client/src/redux/createSlice/LoginInfoSlice.js
client/src/services/userInfoService.js

- token refresh hook 추가
- member page, video page에 반영

[FE] token refresh hook 추가, member page, video page에 반영

---

admin/src/App.tsx
admin/src/components/navBar/NavBar.tsx
admin/src/components/navBar/NavButton.tsx
admin/src/components/reportPage/ChannelReportList.tsx
admin/src/components/reportPage/NoticeReportList.tsx
admin/src/components/reportPage/ReviewReportList.tsx
admin/src/components/reportPage/VideoReportList.tsx
admin/src/hooks/useLocation.ts
admin/src/hooks/useToken.ts
admin/src/pages/reports/ReportChannelPage.tsx
admin/src/pages/reports/ReportNoticePage.tsx
admin/src/pages/reports/ReportReviewPage.tsx
admin/src/pages/reports/ReportVideoPage.tsx
admin/src/services/reprotService.ts
admin/src/types/reportDataType.ts
admin/tsconfig.json

[FE] 신고 내역 조회

---

client/src/atoms/inputs/Inputs.js
client/src/components/DetailPage/ReviewList.js
client/src/components/UploadPage/CourseUpload.js
client/src/components/contentListItems/NoticeItem.js
client/src/components/contentListItems/Setting.js
client/src/pages/contents/LectureListPage.js

[FE] 클라이언트 수정

---

admin/src/components/CustomerService/ChatList.tsx
admin/src/pages/chats/ChatRoomPage.tsx
client/src/components/helpCenter/HelpCenter.js
client/src/components/helpCenter/HelpChatLists.js
client/src/pages/contents/ToTopButton.js

[FE] client, admin 다른 아이디 연결시 오류 해결

[FE] client, admin 다른 아이디 연결시 오류 해결

---

client/src/components/contentListItems/Setting.js

[FE] Setting.js CSS red border 삭제

[FE] Setting.js CSS red border 삭제

---

client/src/hooks/useLogout.js
client/src/pages/contents/LectureListPage.js

[FE] redux imgUrl 이름 통일
